import type {
  KnowledgeEdge,
  KnowledgeNodeDefinition,
} from "../../contracts/src/index.ts";

export const ATLAS_SCOPE = "理解 Transformer 与大模型推理";
export const ATLAS_SCOPE_VERSION = "2026.08-demo-v1";

export const KNOWLEDGE_NODES: KnowledgeNodeDefinition[] = [
  {
    id: "ai-systems",
    label: "大模型知识域",
    labelEn: "LLM SYSTEMS",
    group: "领域",
    categoryPath: ["人工智能", "大语言模型"],
    description: "围绕 Transformer 原理、训练、推理与应用构成的目标知识地图。",
    whyItMatters: "这是本次覆盖率的明确分母，所有百分比只相对于该范围计算。",
    x: 80,
    y: 390,
    weight: 0,
    keywords: [],
    prerequisites: [],
    outcomes: ["linear-algebra", "probability", "neural-networks", "nlp"],
    kind: "domain",
  },
  {
    id: "linear-algebra",
    label: "线性代数",
    labelEn: "LINEAR ALGEBRA",
    group: "基础",
    categoryPath: ["基础学科", "数学", "线性代数"],
    description: "向量、矩阵与线性变换，是注意力计算的表达语言。",
    whyItMatters: "不理解矩阵乘法，就难以解释 Q、K、V 如何批量计算相关性。",
    x: 260,
    y: 105,
    weight: 1.1,
    keywords: ["线性代数", "矩阵乘法", "向量空间"],
    prerequisites: ["ai-systems"],
    outcomes: ["embeddings", "softmax", "attention"],
  },
  {
    id: "probability",
    label: "概率与信息论",
    labelEn: "PROBABILITY",
    group: "基础",
    categoryPath: ["基础学科", "数学", "概率与信息论"],
    description: "概率分布、交叉熵和最大似然构成语言模型训练目标的基础。",
    whyItMatters: "它解释模型为什么能把“预测下一个词”转化为可优化的损失。",
    x: 260,
    y: 260,
    weight: 1.15,
    keywords: ["概率分布", "交叉熵", "最大似然", "信息论"],
    prerequisites: ["ai-systems"],
    outcomes: ["softmax", "pretraining"],
  },
  {
    id: "neural-networks",
    label: "神经网络",
    labelEn: "NEURAL NETWORKS",
    group: "基础",
    categoryPath: ["人工智能", "深度学习", "神经网络"],
    description: "由参数化层、激活函数与优化过程组成的通用函数逼近器。",
    whyItMatters: "Transformer 是神经网络架构，而不是独立于深度学习的黑盒。",
    x: 260,
    y: 415,
    weight: 1.2,
    keywords: ["神经网络", "激活函数", "参数化层"],
    prerequisites: ["ai-systems"],
    outcomes: ["backprop", "sequence-models", "residual"],
  },
  {
    id: "nlp",
    label: "NLP 基础",
    labelEn: "NLP BASICS",
    group: "基础",
    categoryPath: ["人工智能", "自然语言处理"],
    description: "文本切分、词元、语言表示与序列任务的基本问题。",
    whyItMatters: "它把自然语言变成模型能够接收和输出的离散序列。",
    x: 260,
    y: 570,
    weight: 0.9,
    keywords: ["自然语言处理", "词元", "tokenization", "token"],
    prerequisites: ["ai-systems"],
    outcomes: ["embeddings", "sequence-models"],
  },
  {
    id: "embeddings",
    label: "向量表示",
    labelEn: "EMBEDDINGS",
    group: "表示",
    categoryPath: ["人工智能", "表示学习", "词嵌入"],
    description: "将离散词元映射到连续向量空间，使语义关系可以被计算。",
    whyItMatters: "注意力操作的不是原始文字，而是每个 token 的向量表示。",
    x: 455,
    y: 90,
    weight: 1.1,
    keywords: ["词嵌入", "embedding", "向量表示"],
    prerequisites: ["linear-algebra", "nlp"],
    outcomes: ["attention", "positional-encoding"],
  },
  {
    id: "softmax",
    label: "Softmax",
    labelEn: "SOFTMAX",
    group: "表示",
    categoryPath: ["深度学习", "算子", "Softmax"],
    description: "把一组实数映射为总和为 1 的权重分布。",
    whyItMatters: "它把注意力分数变成对不同 token 的可解释权重。",
    x: 455,
    y: 225,
    weight: 1,
    keywords: ["softmax", "归一化指数"],
    prerequisites: ["linear-algebra", "probability"],
    outcomes: ["attention", "self-attention"],
  },
  {
    id: "backprop",
    label: "反向传播",
    labelEn: "BACKPROP",
    group: "表示",
    categoryPath: ["深度学习", "优化", "反向传播"],
    description: "通过链式法则把损失梯度传播到每个可训练参数。",
    whyItMatters: "它解释 Transformer 的参数如何从数据中真正学到表示。",
    x: 455,
    y: 360,
    weight: 1,
    keywords: ["反向传播", "梯度下降", "链式法则"],
    prerequisites: ["neural-networks"],
    outcomes: ["pretraining", "fine-tuning"],
  },
  {
    id: "sequence-models",
    label: "序列建模",
    labelEn: "SEQUENCE MODELS",
    group: "表示",
    categoryPath: ["人工智能", "深度学习", "序列模型"],
    description: "处理顺序依赖、上下文与可变长度输入的模型范式。",
    whyItMatters: "理解 RNN 的顺序瓶颈，才能理解 Transformer 并行化的价值。",
    x: 455,
    y: 515,
    weight: 1,
    keywords: ["序列模型", "循环神经网络", "rnn", "长程依赖"],
    prerequisites: ["neural-networks", "nlp"],
    outcomes: ["attention"],
  },
  {
    id: "attention",
    label: "注意力机制",
    labelEn: "ATTENTION",
    group: "核心机制",
    categoryPath: ["人工智能", "深度学习", "注意力机制"],
    description: "根据查询与上下文的相关性，动态聚合最有用的信息。",
    whyItMatters: "这是 Transformer 用内容相关性替代固定递归路径的核心机制。",
    x: 650,
    y: 130,
    weight: 1.45,
    keywords: ["注意力机制", "attention", "qkv", "query key value"],
    aliases: ["Attention Mechanism", "注意力", "Q-K-V 注意力"],
    prerequisites: ["embeddings", "softmax", "sequence-models"],
    outcomes: ["self-attention"],
  },
  {
    id: "self-attention",
    label: "自注意力",
    labelEn: "SELF-ATTENTION",
    group: "核心机制",
    categoryPath: ["人工智能", "Transformer", "自注意力"],
    description: "让序列中的每个位置直接读取同一序列的其他位置。",
    whyItMatters: "它在一层中建立任意 token 间的依赖，并支持并行计算。",
    x: 650,
    y: 275,
    weight: 1.5,
    keywords: ["自注意力", "self-attention", "scaled dot-product"],
    aliases: ["Self Attention", "SelfAttention", "缩放点积自注意力"],
    prerequisites: ["attention", "softmax"],
    outcomes: ["multi-head-attention", "transformer-block"],
  },
  {
    id: "residual",
    label: "残差连接",
    labelEn: "RESIDUAL",
    group: "核心机制",
    categoryPath: ["深度学习", "网络结构", "残差连接"],
    description: "把子层输入直接加到输出上，保留信息与梯度通路。",
    whyItMatters: "它让深层 Transformer 更稳定，也使每个子层学习增量变化。",
    x: 650,
    y: 420,
    weight: 1.1,
    keywords: ["残差连接", "residual", "跳跃连接"],
    prerequisites: ["neural-networks"],
    outcomes: ["transformer-block"],
  },
  {
    id: "layer-norm",
    label: "LayerNorm",
    labelEn: "LAYER NORM",
    group: "核心机制",
    categoryPath: ["深度学习", "归一化", "LayerNorm"],
    description: "在单个样本的特征维度上归一化激活值。",
    whyItMatters: "它是稳定深层 Transformer 训练与控制激活尺度的关键组件。",
    x: 650,
    y: 565,
    weight: 1.15,
    keywords: ["layernorm", "layer norm", "层归一化"],
    prerequisites: ["neural-networks"],
    outcomes: ["transformer-block"],
  },
  {
    id: "multi-head-attention",
    label: "多头注意力",
    labelEn: "MULTI-HEAD",
    group: "架构",
    categoryPath: ["人工智能", "Transformer", "多头注意力"],
    description: "在多个投影子空间中并行计算注意力，再合并结果。",
    whyItMatters: "不同注意力头可以同时捕捉位置、语义和句法等不同关系。",
    x: 845,
    y: 145,
    weight: 1.35,
    keywords: ["多头注意力", "multi-head", "多个注意力头"],
    aliases: ["Multi-Head Attention", "MHA", "多头自注意力"],
    prerequisites: ["self-attention"],
    outcomes: ["transformer-block"],
  },
  {
    id: "positional-encoding",
    label: "位置编码",
    labelEn: "POSITION",
    group: "架构",
    categoryPath: ["人工智能", "Transformer", "位置编码"],
    description: "向 token 表示注入顺序或相对位置信息。",
    whyItMatters: "自注意力本身对排列不敏感，没有位置信号就无法区分词序。",
    x: 845,
    y: 285,
    weight: 1.3,
    keywords: ["位置编码", "positional encoding", "rope", "旋转位置编码"],
    aliases: ["Position Encoding", "Positional Embedding", "RoPE"],
    prerequisites: ["embeddings", "self-attention"],
    outcomes: ["transformer-block", "kv-cache"],
  },
  {
    id: "ffn",
    label: "前馈网络 FFN",
    labelEn: "FEED FORWARD",
    group: "架构",
    categoryPath: ["人工智能", "Transformer", "前馈网络"],
    description: "逐 token 应用的两层非线性变换，负责特征加工与容量扩展。",
    whyItMatters: "注意力负责交换信息，FFN 负责在每个位置内部加工信息。",
    x: 845,
    y: 430,
    weight: 1.25,
    keywords: ["前馈网络", "feed-forward", "ffn", "mlp block"],
    prerequisites: ["neural-networks"],
    outcomes: ["transformer-block"],
  },
  {
    id: "transformer-block",
    label: "Transformer Block",
    labelEn: "TRANSFORMER",
    group: "架构",
    categoryPath: ["人工智能", "Transformer", "基本结构"],
    description: "由注意力、前馈网络、残差与归一化组合而成的重复模块。",
    whyItMatters: "它把分散的知识点汇合成可训练、可堆叠的完整架构。",
    x: 1015,
    y: 300,
    weight: 1.6,
    keywords: ["transformer block", "transformer 架构", "编码器", "解码器"],
    aliases: ["Transformer Layer", "Transformer 块", "注意力块"],
    prerequisites: [
      "multi-head-attention",
      "positional-encoding",
      "ffn",
      "residual",
      "layer-norm",
    ],
    outcomes: ["pretraining", "fine-tuning", "kv-cache", "rag"],
  },
  {
    id: "pretraining",
    label: "预训练目标",
    labelEn: "PRETRAINING",
    group: "训练与推理",
    categoryPath: ["大语言模型", "训练", "预训练"],
    description: "通过下一个 token 预测等自监督任务从大规模语料学习参数。",
    whyItMatters: "它连接模型结构、训练数据与最终语言能力的来源。",
    x: 1190,
    y: 95,
    weight: 1.25,
    keywords: ["预训练", "下一个词预测", "next token", "语言模型目标"],
    prerequisites: ["probability", "backprop", "transformer-block"],
    outcomes: ["fine-tuning"],
  },
  {
    id: "fine-tuning",
    label: "微调与 LoRA",
    labelEn: "FINE-TUNING",
    group: "训练与推理",
    categoryPath: ["大语言模型", "训练", "微调"],
    description: "用任务数据继续更新全部或少量参数，使模型适配特定行为。",
    whyItMatters: "它解释通用基础模型如何低成本变成领域或任务模型。",
    x: 1190,
    y: 235,
    weight: 1,
    keywords: ["微调", "fine-tuning", "lora", "参数高效微调"],
    prerequisites: ["backprop", "pretraining", "transformer-block"],
    outcomes: ["rag"],
  },
  {
    id: "kv-cache",
    label: "KV Cache",
    labelEn: "KV CACHE",
    group: "训练与推理",
    categoryPath: ["大语言模型", "推理", "KV Cache"],
    description: "复用历史 token 的 Key 与 Value，避免自回归生成时重复计算。",
    whyItMatters: "它是理解大模型推理延迟、显存占用与长上下文成本的入口。",
    x: 1190,
    y: 375,
    weight: 1.3,
    keywords: ["kv cache", "kv缓存", "键值缓存", "推理缓存"],
    aliases: ["KV-Cache", "Key Value Cache", "键值对缓存"],
    prerequisites: ["self-attention", "positional-encoding", "transformer-block"],
    outcomes: ["quantization"],
  },
  {
    id: "quantization",
    label: "模型量化",
    labelEn: "QUANTIZATION",
    group: "训练与推理",
    categoryPath: ["大语言模型", "推理", "模型量化"],
    description: "用更低精度表示权重或激活，换取更小显存与更快推理。",
    whyItMatters: "它把模型原理连接到真实设备和服务成本。",
    x: 1190,
    y: 515,
    weight: 0.9,
    keywords: ["模型量化", "量化", "int8", "int4"],
    prerequisites: ["transformer-block", "kv-cache"],
    outcomes: [],
  },
  {
    id: "rag",
    label: "RAG 应用",
    labelEn: "RAG",
    group: "应用",
    categoryPath: ["大语言模型", "应用", "检索增强生成"],
    description: "检索外部证据并将其作为上下文交给模型生成答案。",
    whyItMatters: "它是把模型能力连接到个人知识库与可追溯答案的常见方法。",
    x: 1190,
    y: 650,
    weight: 0.85,
    keywords: ["rag", "检索增强生成", "向量检索"],
    aliases: ["Retrieval-Augmented Generation", "检索增强", "知识库问答"],
    prerequisites: ["embeddings", "transformer-block"],
    outcomes: [],
  },
];

export const KNOWLEDGE_EDGES: KnowledgeEdge[] = KNOWLEDGE_NODES.flatMap(
  (node) =>
    node.prerequisites.map((source) => ({
      id: `${source}->${node.id}`,
      source,
      target: node.id,
      relation: source === "ai-systems" ? "contains" : "prerequisite",
    })),
);

export function getKnowledgeNode(id: string) {
  return KNOWLEDGE_NODES.find((node) => node.id === id);
}
